var agora = new Date()
var hora = agora.getHours()
  console.log(`Agora são exatamente ${hora} horas.`)
if (hora > 6 && hora < 11)
  console.log(`Bom dia!`)
else if (hora > 12 && hora < 17)
  console.log(`Boa Tarde!`)
else if (hora > 18 && hora < 24)
  console.log(`Boa Noite!`)
else (hora > 1 && hora < 5)
  console.log(`boa Madrugada!`)